# Generated by Django 2.1.2 on 2019-08-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20190821_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(choices=[('MPEG3', 'MP3'), ('MPEG4', 'MP4'), ('WAV', 'WAV')], default='MPEG3', max_length=100),
        ),
    ]
