# Generated by Django 2.1.2 on 2019-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20190821_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='real_song',
            field=models.FileField(default='music/leesun.mp3', upload_to='music'),
        ),
    ]
