# Generated by Django 2.1.2 on 2019-08-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_song_real_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='real_song',
            field=models.FileField(default='/media/music/leesun.mp3', upload_to='music'),
        ),
    ]
