# Generated by Django 2.1.2 on 2019-09-23 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0007_auto_20190827_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newplaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='file_type',
            field=models.CharField(choices=[('MPEG3', 'MP3'), ('MPEG4', 'MP4')], default='MPEG3', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='real_song',
            field=models.FileField(default='/media/music/leesun.mp3', help_text='Hint: Files must be MP3 or MP4', upload_to='music'),
        ),
        migrations.AddField(
            model_name='newplaylist',
            name='songs',
            field=models.ManyToManyField(to='tutorials.Song'),
        ),
    ]
