# Generated by Django 2.1.2 on 2019-09-29 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_auto_20190923_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='newplaylist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newplaylist',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
